#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build:
    context: ..
    dockerfile: docker/dockerfile.cpu
  image: pomelo925/2025-fall-ai-course:cpu

  volumes:
    # GUI support for applications
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix
    
    # Workspace volume
    - ../workspace:/workspace

  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/tmp/.docker.xauth

  # Container communication settings
  network_mode: host
  ipc: host
  
  # Container settings
  tty: true
  stdin_open: true
  privileged: true
  stop_grace_period: 1s

##############################
###   Container Services   ###
##############################
services:
  dev:
    <<: *common
    container_name: cpu-dev
    working_dir: /workspace/openpilot
    command: >
      bash -c "tail -f /dev/null"


